-- Phase 14 — Avatar-led practice + landmark-backed delivery report.
-- Adds a stored, deterministic presence summary (a neutral rollup of the
-- observable delivery measurements) to delivery_analyses. This is NOT a
-- confidence/emotion score; it is generated by a pure function from
-- delivery_metrics and passed through the prohibited-claims linter
-- (PHASE_14_AVATAR_PRACTICE.md §4). No biometric data is introduced.

alter table public.delivery_analyses
  add column presence_summary jsonb;

comment on column public.delivery_analyses.presence_summary is
  'Deterministic neutral rollup of observable delivery measurements '
  '(PHASE_14 §4). Never a confidence/emotion/personality judgment.';
